"""CITATION.cff generated from the canonical record.

CITATION.cff is how GitHub, Zenodo and citation managers learn how a research
output wants to be cited. ORW generates it rather than asking a researcher to
maintain a second copy of the same metadata by hand.

Nothing is inferred. A license that was never declared produces no `license`
field, and the readiness report says so, because a citation file that quietly
invents terms is worse than one that admits a gap.
"""
from __future__ import annotations

from typing import Any, Mapping

from .. import edit
from ._common import investigation, keywords, licenses, own_doi, people, related

CFF_VERSION = "1.2.0"
CFF_TYPE = "dataset"
MESSAGE = "If you use this research workspace, please cite it as below."

GENERATED_MARKER = (
    "# Generated by OpenResearchWorkspace from .research/project.yml."
)
HEADER = (
    f"{GENERATED_MARKER}\n"
    "# Edits here are overwritten; change the canonical record instead.\n"
    "# Regenerate with: orw fair citation\n"
)

# SPDX identifiers common in research outputs. CITATION.cff validates `license`
# against the full SPDX list, so an identifier ORW does not recognize is emitted
# as `license-url` instead of risking an invalid citation file.
SPDX_IDENTIFIERS = frozenset({
    "0BSD", "AGPL-3.0-only", "AGPL-3.0-or-later", "Apache-2.0", "Artistic-2.0",
    "BSD-2-Clause", "BSD-3-Clause", "BSD-4-Clause", "BSL-1.0", "CC-BY-3.0",
    "CC-BY-4.0", "CC-BY-NC-4.0", "CC-BY-NC-ND-4.0", "CC-BY-NC-SA-4.0",
    "CC-BY-ND-4.0", "CC-BY-SA-3.0", "CC-BY-SA-4.0", "CC0-1.0", "CDDL-1.0",
    "ECL-2.0", "EPL-2.0", "EUPL-1.2", "GFDL-1.3-or-later", "GPL-2.0-only",
    "GPL-2.0-or-later", "GPL-3.0-only", "GPL-3.0-or-later", "ISC",
    "LGPL-2.1-only", "LGPL-2.1-or-later", "LGPL-3.0-only", "LGPL-3.0-or-later",
    "MIT", "MPL-2.0", "ODbL-1.0", "ODC-By-1.0", "OSL-3.0", "PDDL-1.0",
    "Unlicense", "Zlib",
})


def _author(person) -> dict[str, Any]:
    if not person.citable_as_person:
        # CFF entity form: honest about the fact that no name parts were given.
        entry: dict[str, Any] = {"name": person.name}
    else:
        entry = {
            "family-names": person.family_name,
            "given-names": person.given_name,
        }
    if person.orcid is not None:
        entry["orcid"] = person.orcid.url
    if person.affiliation:
        entry["affiliation"] = person.affiliation
    if person.email:
        entry["email"] = person.email
    return entry


def _identifiers(data: Mapping[str, Any]) -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    for item in related(data):
        if item.identifier is None:
            continue  # Unrecognized identifiers are reported, not guessed at.
        description = item.title or item.relation
        entry: dict[str, Any] = {
            "type": item.identifier.cff_type,
            "value": (
                item.identifier.url
                if item.identifier.cff_type == "url"
                else item.identifier.value
            ),
        }
        if description:
            entry["description"] = description
        entries.append(entry)
    return entries


def build(data: Mapping[str, Any]) -> dict[str, Any]:
    """The CITATION.cff document as ordered data, before it is rendered."""

    record = investigation(data)
    document: dict[str, Any] = {
        "cff-version": CFF_VERSION,
        "message": MESSAGE,
        "type": CFF_TYPE,
        "title": record.get("title"),
        "abstract": record.get("description"),
    }

    authors = [_author(person) for person in people(data)]
    document["authors"] = authors or None

    words = keywords(data)
    document["keywords"] = list(words) or None

    declared = licenses(data)
    project = declared.get("project")
    if project is not None:
        identifier = str(project["identifier"]).strip()
        if identifier in SPDX_IDENTIFIERS:
            document["license"] = identifier
        url = project.get("url")
        if isinstance(url, str) and url.strip():
            document["license-url"] = url.strip()

    version = record.get("version")
    if isinstance(version, str) and version.strip():
        document["version"] = version.strip()

    doi = own_doi(data)
    if doi is not None:
        document["doi"] = doi.value

    identifiers = _identifiers(data)
    if identifiers:
        document["identifiers"] = identifiers

    return {key: value for key, value in document.items() if value is not None}


def render(data: Mapping[str, Any]) -> str:
    """Render CITATION.cff, deterministically and with the generation header."""

    return HEADER + edit.render_block(build(data), 0)


def is_generated(text: str) -> bool:
    """Whether a CITATION.cff was written by ORW and may be regenerated."""

    return text.lstrip("﻿").startswith(GENERATED_MARKER)
